[features]
seeds = false
skip-lint = false
[programs.localnet]
note = "ANjbSZys9sYrPfywRWk68GhW5eRFQG8qJ3QV3K6csoGE"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "Localnet"
wallet = "/Users/miglesias/.config/solana/id.json"

[scripts]
test1 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/allfunc.ts"
test2 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sectest.ts"
test3 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/add.ts"
test4 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/date.ts"
test5 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/biggersize.ts"
